name: Deploy Portainer to DeployAja

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DeployAja Plan
        uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: plan
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}

      - name: DeployAja Deploy
        uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}

      - name: DeployAja Status
        uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: status
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
